import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AppSwitcher,Icon} from '@base/design-system';
import * as repo from './repository';
import {KINDS,STATUSES,daysUntil,dateBR,money,urgency,reminders,todayISO,userError,needsReview,compareServices} from './domain';
import {ClientForm,ServiceForm,ServiceDetail,RenewalForm,Empty,ErrorBox} from './components';

const APPS=[
  {id:'financeiro',name:'Financeiro',shortName:'FI',description:'Gestão financeira e comercial',href:import.meta.env.DEV?'http://127.0.0.1:5174/':'/',color:'#5a39e6'},
  {id:'not',name:'NOT',shortName:'NOT',description:'Serviços, vencimentos e lembretes',href:'/not/',color:'#5a39e6'},
  {id:'manutencao-sites',name:'Manutenção de sites',shortName:'MS',description:'Sites, contratos e manutenções',href:import.meta.env.VITE_MANUTENCAO_SITES_URL||'https://base-manutencao-sites.vercel.app',color:'#d2694d'},
];
const NAV=[['overview','Visão geral','layout-dashboard'],['services','Serviços','server'],['reminders','Lembretes','bell'],['clients','Clientes do BASE','users']];
function Metric({label,value,icon,tone='',hint,onClick}){return <button className={`not-metric ${tone}`} onClick={onClick}><span>{label}<Icon name={icon} size={19}/></span><strong>{value}</strong><small>{hint}</small></button>;}

export default function App({user,onLogout}){
  const [workspaces,setWorkspaces]=useState(null),[workspace,setWorkspace]=useState(null),[data,setData]=useState({clients:[],services:[]});
  const [view,setView]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
  const [companyName,setCompanyName]=useState('BASE'),[mobileMenu,setMobileMenu]=useState(false),[modal,setModal]=useState(null);
  const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[status,setStatus]=useState('active'),[period,setPeriod]=useState('all');
  const [today,setToday]=useState(todayISO()),epoch=useRef(0);
  useEffect(()=>{const timer=setInterval(()=>setToday(todayISO()),60000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
  async function load(target){const token=++epoch.current;setLoading(true);setError('');try{const result=await repo.loadNot(target.id);if(token===epoch.current){setWorkspace(target);setData(result);}}catch(e){if(token===epoch.current)setError(userError(e));}finally{if(token===epoch.current)setLoading(false);}}
  async function start(){const token=++epoch.current;setError('');setLoading(true);try{const rows=await repo.listWorkspaces(user.id);if(token!==epoch.current)return;setWorkspaces(rows);if(rows.length===1&&rows[0].enabled){await load(rows[0]);}else setLoading(false);}catch(e){if(token===epoch.current){setError(userError(e));setLoading(false);}}}
  useEffect(()=>{start();return()=>{epoch.current++;};},[user.id]);
  async function choose(target){setBusy(true);setError('');try{const id=await repo.activate(target?.id,companyName);await load({...target,id,name:target?.name||companyName,enabled:true});}catch(e){setError(userError(e));}finally{setBusy(false);}}
  function navigate(next){setView(next);setQuery('');setPeriod('all');setStatus('active');setKind('all');setMobileMenu(false);}
  function saved(service){setData(d=>({...d,services:[...d.services.filter(s=>s.id!==service.id),service].sort(compareServices)}));setModal(null);setToast('Serviço salvo no NOT. Nenhuma mensagem enviada.');}
  function clientSaved(client){setData(d=>({...d,clients:[...d.clients.filter(c=>c.id!==client.id),client].sort((a,b)=>a.name.localeCompare(b.name))}));}
  const clientsById=useMemo(()=>new Map(data.clients.map(c=>[c.id,c])),[data.clients]);
  const active=data.services.filter(s=>s.status==='active');
  const overdue=active.filter(s=>daysUntil(s.due_date,today)<0),urgent=active.filter(s=>daysUntil(s.due_date,today)>=0&&daysUntil(s.due_date,today)<=2),upcoming=active.filter(s=>daysUntil(s.due_date,today)>=0&&daysUntil(s.due_date,today)<=30);
  const filtered=data.services.filter(s=>{
    const c=clientsById.get(s.client_id);const match=`${s.name} ${s.identifier} ${s.provider} ${s.notes||''} ${c?.name} ${c?.payload.tradeName||''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
    const group=urgency(s,today).group;
    return match&&(kind==='all'||s.kind===kind)&&(status==='all'||(status==='review'?needsReview(s):s.status===status))&&(period==='all'||(period==='upcoming'?s.status==='active'&&daysUntil(s.due_date,today)>=0&&daysUntil(s.due_date,today)<=30:group===period))&&(view!=='overview'||(s.status==='active'&&daysUntil(s.due_date,today)<=30));
  });
  const planned=active.flatMap(s=>reminders(s,today).map(r=>({...r,service:s}))).filter(r=>Math.abs(daysUntil(r.date,today))<=30).sort((a,b)=>a.date.localeCompare(b.date));
  const goPeriod=p=>{navigate('services');setPeriod(p);};
  const addButton=<button className="not-button" onClick={()=>setModal({type:'edit'})}><Icon name="plus" size={18}/>Novo serviço</button>;
  if(!workspace)return <div className="not-onboarding"><div className="not-onboarding-card"><span className="not-brand">NOT</span><p className="not-eyebrow">BASE · NOT</p><h1>Menos imprevistos.<br/>Vencimentos por perto.</h1><p>Organize domínios, hospedagem, e-mail e serviços TOSS. Seus clientes continuam na mesma central do BASE.</p><ErrorBox error={error}/>{loading?<p role="status">Conferindo seu acesso…</p>:<>
    {workspaces?.length>0?<section><h2>Escolha sua empresa</h2><p>Ao ativar o NOT, os clientes existentes ficam disponíveis aqui. Nenhum cadastro será copiado.</p>{workspaces.map(w=><button key={w.id} className="not-workspace-choice" disabled={busy||(!w.owner&&!w.enabled)} onClick={()=>choose(w)}><span><strong>{w.name}</strong><small>{w.enabled?'Abrir NOT':w.owner?'Ativar NOT e usar clientes do BASE':'Solicite acesso ao administrador'}</small></span><Icon name="arrow-right"/></button>)}</section>:workspaces&&<form onSubmit={e=>{e.preventDefault();choose(null);}}><label className="not-field"><span>Nome da empresa</span><input required maxLength={120} value={companyName} onChange={e=>setCompanyName(e.target.value)}/></label><button className="not-button" disabled={busy}>{busy?'Ativando…':'Começar no NOT'}</button></form>}
    {error&&<button className="not-button secondary" onClick={start}>Tentar novamente</button>}
  </>}<div className="not-onboarding-foot"><a href={APPS[0].href}>Voltar ao Financeiro</a><button onClick={onLogout}>Sair</button></div></div></div>;
  return <div className="not-app">
    {mobileMenu&&<button className="not-backdrop" aria-label="Fechar menu" onClick={()=>setMobileMenu(false)}/>}
    <aside className={`not-sidebar ${mobileMenu?'open':''}`}><AppSwitcher currentApp="not" apps={APPS}/><p className="not-nav-label">Acompanhamento</p><nav>{NAV.map(([id,label,icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon name={icon} size={20}/>{label}</button>)}</nav><div className="not-side-note"><Icon name="bell" size={22}/><strong>Primeiro, prevenir.</strong><p>Um lembrete próximo da data faz diferença.</p><span>Envios desativados</span></div><div className="not-sidebar-foot"><strong>{workspace.name}</strong><small>{user.email}</small>{workspaces?.length>1&&<button onClick={()=>{epoch.current++;setWorkspace(null);setData({clients:[],services:[]});}}>Trocar empresa</button>}<button onClick={onLogout}><Icon name="logout" size={18}/>Sair</button></div></aside>
    <main className="not-main"><header className="not-top"><button className="not-icon not-mobile-toggle" aria-label="Abrir menu" onClick={()=>setMobileMenu(true)}><Icon name="menu-2"/></button><span className="not-top-label">NOT <span>/</span> {NAV.find(n=>n[0]===view)?.[1]}</span><div><span className="not-preview-badge"><i/>Envios desativados</span><button className="not-icon" title="Atualizar dados" aria-label="Atualizar dados" disabled={loading} onClick={()=>load(workspace)}><Icon name="refresh" size={19}/></button></div></header>
      <div className="not-content"><ErrorBox error={error}/>{loading&&<p role="status">Atualizando dados…</p>}
        <header className="not-page-heading"><div><p className="not-eyebrow">{view==='clients'?'Cadastro compartilhado':'Infraestrutura sob controle'}</p><h1>{view==='overview'?'Vencimentos, sem surpresas.':view==='services'?'Serviços dos clientes':view==='reminders'?'Prévias de lembretes':'Clientes do BASE'}</h1><p>{view==='overview'?'Acompanhe o que vence e prepare o próximo contato.':view==='services'?'Domínios, hospedagem, e-mail e recorrências TOSS.':view==='reminders'?'Datas calculadas a partir do vencimento. Nenhuma mensagem enviada.':'A mesma base usada pelo Financeiro, sem recadastrar.'}</p></div>{view==='clients'?<button className="not-button" onClick={()=>setModal({type:'client'})}><Icon name="plus" size={18}/>Novo cliente</button>:addButton}</header>
        {view==='overview'&&<><section className="not-metrics" aria-label="Resumo dos vencimentos"><Metric label="Vencidos" value={overdue.length} icon="alert-circle" tone="danger" hint="Precisam de conferência" onClick={()=>goPeriod('overdue')}/><Metric label="Hoje e próximos 2 dias" value={urgent.length} icon="clock" tone="warning" hint="Prioridade de acompanhamento" onClick={()=>goPeriod('urgent')}/><Metric label="Nos próximos 30 dias" value={upcoming.length} icon="calendar" hint={`${money(upcoming.reduce((sum,s)=>sum+(s.amount_cents||0),0))} em valores informados`} onClick={()=>goPeriod('upcoming')}/><Metric label="Serviços ativos" value={active.length} icon="server" hint={`${new Set(active.map(s=>s.client_id)).size} clientes acompanhados`} onClick={()=>navigate('services')}/></section><section className="not-guide"><div className="not-guide-icon"><Icon name="bell" size={26}/></div><div><strong>30, 15 e 2 dias. O cuidado começa antes.</strong><p>Prepare os lembretes agora. E-mail e WhatsApp serão conectados em uma próxima etapa.</p></div><button className="not-text-button" onClick={()=>navigate('reminders')}>Ver prévias <Icon name="arrow-right" size={16}/></button></section></>}
        {data.services.some(needsReview)&&view==='overview'&&<section className="not-guide"><div><strong>{data.services.filter(needsReview).length} serviços com dados para revisar</strong><p>Vencimentos antigos foram preservados. Cadastros incompletos ficam pausados, sem lembretes.</p></div><button className="not-text-button" onClick={()=>{navigate('services');setStatus('review');}}>Revisar importação <Icon name="arrow-right" size={16}/></button></section>}
        {(view==='services'||view==='overview')&&<section className="not-panel"><div className="not-panel-heading"><div><h2>{view==='overview'?'Próximos da sua atenção':'Todos os serviços'}</h2><p>{view==='overview'?'Vencidos e vencimentos nos próximos 30 dias.':`${filtered.length} serviços encontrados`}</p></div></div><div className="not-filters"><label className="not-search"><Icon name="search" size={18}/><input aria-label="Buscar serviços" placeholder="Buscar cliente, domínio ou serviço" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar tipo" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Todos os tipos</option>{Object.entries(KINDS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{view==='services'&&<><select aria-label="Filtrar situação" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas as situações</option><option value="review">Revisar importação</option>{Object.entries(STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Filtrar vencimento" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Todos os vencimentos</option><option value="overdue">Vencidos</option><option value="urgent">Hoje a 2 dias</option><option value="upcoming">Até 30 dias</option><option value="later">Mais de 30 dias</option></select></>}</div>
          {filtered.length?<div className="not-service-list">{filtered.map(service=>{const client=clientsById.get(service.client_id),badge=urgency(service,today);return <button className="not-service-row" key={service.id} onClick={()=>setModal({type:'detail',service})}><span className="not-service-symbol"><Icon name={service.kind==='domain'?'world':service.kind==='email'?'mail':'server'} size={23}/></span><span className="not-service-info"><strong>{service.name}</strong><span>{client?.payload.tradeName||client?.name} {service.identifier&&`· ${service.identifier}`}</span><small>{KINDS[service.kind]} · {service.provider||'Fornecedor a confirmar'}{needsReview(service)&&' · Revisar dados'}</small></span><span className="not-service-amount"><strong>{money(service.amount_cents)}</strong><small>{service.payee||'Beneficiário a confirmar'}</small></span><span className="not-service-due"><strong>{dateBR(service.due_date)}</strong><span className={`not-badge ${badge.tone}`}>{badge.label}</span></span><Icon name="chevron-right" size={18}/></button>;})}</div>:<Empty title={data.services.length?'Nenhum serviço neste filtro':'Seu primeiro vencimento começa aqui'} action={!data.services.length&&addButton}>{data.services.length?'Altere os filtros ou consulte todos os serviços.':`${data.clients.length} clientes já disponíveis na central. Cadastre um serviço para acompanhar o vencimento.`}</Empty>}
        </section>}
        {view==='reminders'&&<section className="not-panel"><div className="not-panel-heading"><div><h2>Agenda de prévias</h2><p>De 30 dias atrás a 30 dias à frente · horário de São Paulo</p></div><span className="not-badge muted">Não é uma fila de envio</span></div>{planned.length?<div className="not-reminder-list">{planned.map(r=><button key={`${r.service.id}-${r.days}`} onClick={()=>setModal({type:'detail',service:r.service})}><time>{dateBR(r.date)}</time><span><strong>{r.service.name}</strong><small>{clientsById.get(r.service.client_id)?.name} · {r.days} dias antes do vencimento</small></span><span className={`not-badge ${r.date===today?'accent':'muted'}`}>{r.label}</span></button>)}</div>:<Empty title="Sem prévias neste período">Cadastre serviços ativos e configure os dias de antecedência para ver as datas aqui.</Empty>}</section>}
        {view==='clients'&&<section className="not-panel"><div className="not-filters"><label className="not-search"><Icon name="search" size={18}/><input aria-label="Buscar clientes" placeholder="Buscar cliente ou CPF/CNPJ" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="not-client-list">{data.clients.filter(c=>`${c.name} ${c.payload.tradeName||''} ${c.payload.cnpj||''}`.toLowerCase().includes(query.toLowerCase())).map(c=><div key={c.id}><span className="not-avatar">{c.name.slice(0,2).toUpperCase()}</span><span><strong>{c.payload.tradeName||c.name}</strong><small>{c.payload.fin?.email||c.payload.email||'Contato a completar'} · {data.services.filter(s=>s.client_id===c.id).length} serviços</small></span><span className={`not-badge ${c.archived_at?'muted':'success'}`}>{c.archived_at?'Arquivado':'Central BASE'}</span><button className="not-icon" aria-label={`Editar ${c.name}`} onClick={()=>setModal({type:'client',client:c})}><Icon name="pencil" size={18}/></button></div>)}</div>{!data.clients.length&&<Empty title="Uma base para todos os apps">O primeiro cliente cadastrado aqui também ficará disponível no Financeiro da mesma empresa.</Empty>}</section>}
        <p className="not-bottom-note">NOT acompanha vencimentos. Pagamentos são feitos diretamente ao fornecedor ou à TOSS.</p>
      </div>
    </main>
    {toast&&<div className="not-toast" role="status"><Icon name="circle-check" size={18}/>{toast}</div>}
    {modal?.type==='edit'&&<ServiceForm workspace={workspace} service={modal.service} clients={data.clients} onClientSaved={clientSaved} onClose={()=>setModal(null)} onSaved={saved}/>}
    {modal?.type==='client'&&<ClientForm workspace={workspace} client={modal.client} onClose={()=>setModal(null)} onSaved={c=>{clientSaved(c);setModal(null);setToast('Cliente salvo na central do BASE.');}}/>}
    {modal?.type==='detail'&&<ServiceDetail workspace={workspace} service={modal.service} client={clientsById.get(modal.service.client_id)} onClose={()=>setModal(null)} onEdit={()=>setModal({...modal,type:'edit'})} onRenew={()=>setModal({...modal,type:'renew'})}/>}
    {modal?.type==='renew'&&<RenewalForm workspace={workspace} service={modal.service} onClose={()=>setModal(null)} onSaved={saved}/>}
  </div>;
}

